@startuml
package "Web Entry" {
    [BatchReorganizeController] as Web
}

package "Spring Batch & Concurrency" {
    [LockProvider (ShedLock)] as Lock
    [MongoIndexedFileItemReader] as Reader
    [AsyncItemProcessor] as Processor
    [SftpMoveAndIndexItemWriter] as Writer
    [ThreadPoolTaskExecutor] as TaskExec
}

package "Service Layer" {
    [StartReorganizeFullService] as AppSvc
    [FileReorganizationService] as DomainSvc
}

package "Infrastructure Connectors" {
    [CachingSessionFactory (SFTP Pool)] as Pool
    [SftpRemoteFileTemplate] as Template
}

Web --> AppSvc : "execute()"
AppSvc ..> Lock : "Verifica Bloqueo"
AppSvc --> Reader : "Carga items"
Reader --> Processor : "ArchivoLegacy"
Processor --> DomainSvc : "Calcula Rutas"
Processor ..> TaskExec : "Paralelismo"
Writer --> Template : "Operaciones SFTP"
Template --> Pool : "Pide/Devuelve Sesión"
@enduml